# This is a config for E2B sandbox template.
# You can use template ID (84vfi2g99100wsn1pcju) or template name (vibe-app-demo-2) to create a sandbox:

# Python SDK
# from e2b import Sandbox, AsyncSandbox
# sandbox = Sandbox("vibe-app-demo-2") # Sync sandbox
# sandbox = await AsyncSandbox.create("vibe-app-demo-2") # Async sandbox

# JS SDK
# import { Sandbox } from 'e2b'
# const sandbox = await Sandbox.create('vibe-app-demo-2')

team_id = "d50ec582-3158-431d-aac7-3255ba2d46d0"
start_cmd = "/compile_page.sh"
dockerfile = "e2b.Dockerfile"
template_name = "vibe-app-demo-2"
template_id = "84vfi2g99100wsn1pcju"
